# Generated by Django 4.0.4 on 2022-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_order_payment_completed_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
